# Generated by Django 4.1.6 on 2023-02-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tag_post_archived_post_github_post_overleaf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
